#ifndef HARDWARE_SETUP_H
#define HARDWARE_SETUP_H

#define TIMER_DISPLAY_INTERVAL 499
#define HSI_CLOCK_SPEED 16000000
#define TIMER_PID_LOOP_INTERVAL 79
#define TIMER_PRESCALER_VALUE 15999
#define PWM_TIMER_PRESCALER_VALUE 15
#define PWM_TIMER_ARR_VALUE 999
#define PWM_DEFAULT_DUTY_CYCLE 499
#define APB_CLOCK_SPEED 16.0
#define IC2_TRISE 300
#define BAUD_RATE 115200

void hardware_setup(void);

#endif